version: '3.8'

services:
  # 0. CI/CD
  jenkins:
    image: jenkins/jenkins:${JENKINS_TAG}
    container_name: jenkins-docker
    user: ${JENKINS_USER}            # -u root 설정
    restart: always
    ports:
      - "${HOST_IP}:${JENKINS_PORT}:8080"       # 젠킨스 웹 UI, 외부 노출 차단, Nginx에서만 받음
      - "50000:50000"     # 에이전트용
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # 호스트 도커 제어용
      - jenkins_home:/var/jenkins_home              # 데이터 보존
    networks:
      - gourmet-net
  # 1. Database & Cache
  mysql:
    image: mysql:${DB_TAG}
    container_name: mysql-gourmet
    restart: always
    ports:
      - "${HOST_IP}:${DB_PORT}:3306"
    networks:
      - gourmet-net
    env_file:
      - .env
    volumes:
      - ${DB_DATA}:/var/lib/mysql
  redis:
    image: redis:${REDIS_TAG}
    container_name: redis-gourmet
    restart: always
    ports:
      - "${HOST_IP}:${REDIS_PORT}:6379"
    networks:
      - gourmet-net
    env_file:
      - .env
    volumes:
      - ${REDIS_CONF}:/usr/local/etc/redis/redis.conf
      - ${REDIS_DATA}:/data
    command: >
      sh -c 'redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"'
  garage:
    image: dxflrs/garage:${GARAGE_TAG}
    container_name: garage
    restart: always
    ports:
      - "${HOST_IP}:${GARAGE_S3_PORT}:3900"
      - "${HOST_IP}:${GARAGE_RPC_PORT}:3901"
      - "${HOST_IP}:${GARAGE_ADMIN_PORT}:3902"
    volumes:
      - ${GARAGE_DIR}/garage.toml:/etc/garage/garage.toml
      - ${GARAGE_DIR}/meta:/var/lib/garage/meta
      - ${GARAGE_DIR}/data:/var/lib/garage/data
    command: ["/garage", "-c", "/etc/garage/garage.toml", "server"]
    networks:
      - gourmet-net


  # 2. Main Application
  gourmet-app:
    image: ${DOCKER_REGISTRY}/gourmet-backend:${APP_TAG}
    container_name: gourmet-backend-app
    ports:
      - "${HOST_IP}:${APP_DEPLOY_PORT}:8080"
    networks:
      - gourmet-net
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul # 시간대 설정
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
  # 3. Monitoring
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus
    ports:
      - "${HOST_IP}:${PROMETHEUS_PORT}:9090"
    volumes:
      - ${MONITORING_CONFIG_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - gourmet-net

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_TAG}
    container_name: node-exporter
    ports:
      - "${HOST_IP}:${NODE_EXPORTER_PORT}:9100"
    networks:
      - gourmet-net
    restart: always

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: grafana
    ports:
      - "${HOST_IP}:${GRAFANA_PORT}:3000"
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
    restart: always
    networks:
      - gourmet-net

volumes:
  prometheus-data:
    external: true
  jenkins_home:
    external: true

networks:
  gourmet-net:
    external: true # 이미 만들어진 네트워크 사용